### ISSUE TITLE
Initial Research - randomization, card layout, dynamic buttons and text

### ISSUE THREAD

**Issue by amtjitro** [cse110-sp23-group25/latte-art#4]
# Task

- [ ] Research how to randomize the cards that appear ("cards" will most likely be images, but let's see if that's possible)
- [ ] Research how to animate cards to layout in the 5 card format
- [ ] Research how to make buttons & text appear and disappear depending on what stage of the fortune telling ceremony we are in

# Due Date
Week 7 — Monday, May 12th

# Documents
Add in your research to [this](https://docs.google.com/document/d/1_lkme7r0zxiIhI6CJuKTn_uJJUq4BHwx4ldEDevFs7c/edit?usp=sharing) document
