### ISSUE TITLE
CI/CD Pipeline Phase 1

### ISSUE THREAD

**Issue by amtjitro** [cse110-sp23-group25/latte-art#5]
# Task
Look into CI/CD pipeline tools such as
- linting and code style enforcement (may happen in pipeline and/or in editor)
- code quality via tool  (ex. Codeclimate, Codacy, etc.)
- code quality via human review (ex. Pull Requests)
- unit tests via automation (ex. Jest, Tape, Ava, Cypress, Mocha/Chai, etc.)*
- documentation generation via automation (ex. JSDocs)

As we don't have much code right now, we can try to test it out on the 8-ball repo.

# Due Date
Sunday, May 21st

# Deliverables
- [ ] phase1.png - a diagram of your phase 1 build pipeline (can be phase1.drawio.png if using draw.io)
- [ ] phase1.md - a short 2 page (roughly) status on the pipeline in terms of what is currently functional (and what is planned or in progress). Embed your diagram in the markdown file.
- [ ] phase1.mp4 - a no more than 2 min video demonstration of the pipeline
